# model
num_joints: 21
num_classes: 12
classifier_name: "poseresnet_with_aug"
detector_name: "SSDLite"

# data
file_path: "data/hagrid/detect"

classes_dict:
  call: 0
  dislike: 1
  fist: 2
  like: 3
  mute: 4
  ok: 5
  one: 6
  palm: 7
  peace: 8
  peace_inverted: 9
  stop: 10
  stop_inverted: 11
