# model
num_joints: 21
num_classes: 10
model_name: "poseresnet_test6_image_resize"

# dataset
data_path: "hagrid/hagrid_test"

classes_dict:
  call: 0
  dislike: 1
  fist: 2
  like: 3
  mute: 4
  ok: 5
  one: 6
  palm: 7
  peace: 8
  stop: 9

batch_size: 32
img_size: 256
sigma: 3

# result
display_results: False
